version: '3.8'
services:
  ocr_app:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload

  react-app:
    build: ./web
    ports:
      - "3000:80"
    volumes:
      - ./web:/app
    depends_on:
      - ocr_app