version: '3.8'
services:
  ocr_app:
    build: ./api
    image: ocr_app:latest
    container_name: ocr_app
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - ./api:/app/api
    command: uvicorn api.app:app --host 0.0.0.0 --port 5000 --reload
    env_file:
      - .env
    depends_on:
      - celery_worker
    networks:
      - mynetwork

  celery_worker:
    image: ocr_app:latest
    container_name : celery_worker
    command: celery -A api.worker worker --loglevel=info
    volumes:
      - ./api:/app/api
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - mynetwork

  react-app:
    build: ./web
    container_name: react_app
    ports:
      - "3000:80"
    volumes:
      - ./web:/app
    depends_on:
      - ocr_app
    env_file:
      - .env
    networks:
      - mynetwork

  redis:
    image: redis:7
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
