version: '3.8'
services:
  ocr-app:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload

  react-app:
    image: node:22.15.0-alpine
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    depends_on:
      - ocr-app
    command: npm run dev -- --host 0.0.0.0 --port 3000