server {
  listen 80;

  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

   # This location block proxies API requests to the backend
  location /api/ {
        # The key is to use the internal Docker network name for proxy_pass
        proxy_pass http://ocr_app:5000/;
        # These headers ensure the backend gets the correct client info
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
  }

}
